# Generated by Django 3.2.4 on 2021-06-18 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UK', 'UK'), ('India', 'India')], max_length=10)),
                ('Account_Holder_Fname', models.CharField(max_length=100)),
                ('Account_Holder_Mname', models.CharField(default='', max_length=100)),
                ('Account_Holder_Lname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Phone Number is not valid', regex='^(?:\\s+|)((0|(?:(\\+|)91))(?:\\s|-)*(?:(?:\\d(?:\\s|-)*\\d{9})|(?:\\d{2}(?:\\s|-)*\\d{8})|(?:\\d{3}(?:\\s|-)*\\d{7}))|\\d{10})(?:\\s+|)')])),
                ('Account_no', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='Account Number is not valid', regex='[0-9]{9,18}')])),
                ('bank_br', models.TextField()),
                ('br_id', models.CharField(max_length=122)),
                ('ifsc', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
